log_level: warning
sandbox:
  use: deerflow.sandbox.local:LocalSandboxProvider
  allow_host_bash: false
tools:
  - name: web_search
    group: search
    use: deerflow.community.ddg_search.tools:web_search_tool
